### ISSUE TITLE
heap-buffer-overflow2 in NanoMQ

### ISSUE THREAD

**Issue by songxpu** [emqx/nanomq#1154]
**Describe the bug**
We (School of Cyber Science and Technology, Shandong University) found that NanoMQ can cause buffer overflow when it processes malformed SUBSCRIBE messages. 
This vulnerability is different from https://github.com/emqx/nanomq/issues/1153

**Expected behavior**

If Asan is enabled at compile time, the NanoMQ crashes and displays ASAN information.

**Actual Behavior**

If Asan is enabled at compile time, the NanoMQ crashes and displays ASAN information, which can cause DOS.

**To Reproduce**

Similarly, we will send a vulnerability POC via email (jaylin@emqx.io)  to help developers fix this vulnerability.

![image](https://user-images.githubusercontent.com/44093631/231413709-06fbbc79-46df-4b9b-b149-8369d50c9305.png)

**Environment Details**
 - NanoMQ version：master branch version commit #a72347c （As it is also the current HEAD version of [gitee](https://gitee.com/emqx/nanomq?_from=gitee_search) ）
 - Operating system and version：Ubuntu 20.04
 - Compiler and language used：gcc 9.4.0 clang 10.0.0
 - testing scenario

1. start nanomq with ./nanomq start
2. Send the packet：nc 127.0.0.1 1883 < ./poc2.raw
3. NanoMQ crashes

**Comment by JaylinYu** [comment]
**Describe the bug**

We found that NanoMQ can cause a buffer overflow when it processes malformed messages.
This vulnerability is different from Github Issue https://github.com/emqx/nanomq/issues/1154

Although a fix（https://github.com/nanomq/NanoNNG/pull/509） has been made for Github Issue 
 https://github.com/emqx/nanomq/issues/1154, the problem has not been completely fixed.

This seems to be triggered at different locations

By School of Cyber Science and Technology, Shandong University

**Expected behavior**

If Asan is enabled at compile time, the NanoMQ crashes and displays ASAN information.

**Actual Behavior**

If Asan is enabled at compile time, the NanoMQ crashes and displays ASAN information, which can cause DOS.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

**Environment Details**
NanoMQ version：master branch version commit #8c54cd7,  NanoNNG Git Commit#971b7d02
Operating system and version：Ubuntu 20.04
Compiler and language used：gcc 9.4.0 clang 10.0.0
testing scenario
start nanomq with ./nanomq start
Send the packet：nc 127.0.0.1 1883 < ./poc.raw
NanoMQ crashes

![image](https://user-images.githubusercontent.com/44093631/232202898-af60cc70-635c-4610-b5d0-bfb77e4de301.png)


[poc.zip](https://github.com/emqx/nanomq/files/11238923/poc.zip)

**Comment by gazer-star** [comment]
https://github.com/emqx/nanomq/issues/1167#issuecomment-1514208147 :
I also found this vulnerability with different POC([1167-poc.zip](https://github.com/emqx/nanomq/files/11269489/1167-poc.zip)) a few days ago. You can refer to this POC for vulnerability verification

- Start nanomq: ./nanomq start
- Send the packet: nc 127.0.0.1 1883 < 1167-poc.raw

```
=================================================================
==3728041==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60700001aa81 at pc 0x000000600cf9 bp 0x7f01f1c7e7b0 sp 0x7f01f1c7e7a8
READ of size 1 at 0x60700001aa81 thread T13 (nng:task)
    #0 0x600cf8 in nmq_subinfo_decode /nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:1561:3
    #1 0x611c09 in nano_pipe_recv_cb /nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:1013:8
    #2 0x5b55ae in nni_task_exec /nanomq/nng/src/core/taskq.c:144:3
    #3 0x815698 in tcptran_pipe_recv_cb /nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:858:2
    #4 0x5b467b in nni_taskq_thread /nanomq/nng/src/core/taskq.c:50:4
    #5 0x5b7d4c in nni_thr_wrap /nanomq/nng/src/core/thread.c:94:3
    #6 0x5c78e0 in nni_plat_thr_main /nanomq/nng/src/platform/posix/posix_thread.c:266:2
    #7 0x7f01fad25608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    #8 0x7f01faab1132 in clone /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
